Feature create payment object
SuperFrog-Scheduler-2024/backend pull request #7
Opened 2024-04-01 01:53 UTC by ofuchia

For this project, Intellij doesn't automatically recognize Spring annotations on my end. Please let me know if you are having the same problem, especially with the StudentPaymentRepository which shows as an error on my side (see my comment). I went ahead and manually imported the paths for the annotations. This might be a sign something is missing from the pom.xml.

2024-04-01 01:57 UTC, dehadeaaryan requested changes
Since the pom.xml file was changed to add jpa, you will have to rebuild it. So go to pom.xml and then click on the rebuild with maven button on the top right.

2024-04-01 01:57 UTC, dehadeaaryan commented on src/main/java/edu/tcu/cs/superfrogschedulerbackend/StudentPayment/StudentPayment.java
> +public class StudentPayment implements Serializable {
This should be an Entity

2024-04-05 21:34 UTC, ofuchia commented on src/main/java/edu/tcu/cs/superfrogschedulerbackend/StudentPayment/StudentPayment.java
> +public class StudentPayment implements Serializable {
Updated. Thank you.

2024-04-05 21:41 UTC, dehadeaaryan approved these changes

2024-04-05 21:41 UTC, merged